#!/bin/bash

if [ -z "$1" ]
then
    EUREKA_SERVER_HOST=localhost
else
    EUREKA_SERVER_HOST=$1
fi

echo http://$EUREKA_SERVER_HOST:8761/eureka/apps
curl -s -H "Accept: application/json" http://$EUREKA_SERVER_HOST:8761/eureka/apps | jq '.applications.application[] | {service: .name, instanceId: .instance[].instanceId, ip: .instance[].ipAddr, port: .instance[].port."$"}'

