discovery:
  image: binblee/discovery
  ports:
    - "8761:8761"

book:
  image: binblee/book
  links:
    - discovery

review:
  image: binblee/review
  links:
    - discovery

bookreview:
  image: binblee/bookreview
  links:
    - discovery

edge:
  image: binblee/edge
  links:
    - discovery
  ports:
    - "8765:8765"