server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

zuul:
  ignoredServices: "*"
  routes:
    bookreview:
      path: /br/**