server:
  port: 8765
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

zuul:
  ignoredServices: "*"
  routes:
    bookreview:
      path: /br/**